# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ff7859732bb30bc84b4a2def77dd46a5253fd6f67be170509598fbad297077622e7625d0ce2ccdece304da81f8aabc2e5b0f79e7221274abe4bcb8a7c69c0e3

test:
  secret_key_base: cd8479faee391de53f2d20a8b781143c1d5a440d37689e330f25cdf504a0e18e005c2695ad279c5e8a382ceeb19dec606d0c2a17e58d925cc18b58c0d81e3c55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
